apiVersion: tf-gapi.lukerops.com/v1alpha1
kind: CustomResourceDefinition
metadata:
  name: actionssecret.github.token-router.lukerops.com
spec:
  group: github.token-router.lukerops.com
  kind: ActionsSecret
  versions:
    - name: v1alpha1
      specSchema:
        type: object
        properties:
          secretName:
            type: string
          repository:
            type: string
          organization:
            type: string
