apiVersion: tf-gapi.lukerops.com/v1alpha1
kind: CustomResourceDefinition
metadata:
  name: serviceaccountkey.gcp.token-router.lukerops.com
spec:
  group: gcp.token-router.lukerops.com
  kind: ServiceAccountKey
  versions:
    - name: v1alpha1
      specSchema:
        type: object
        properties:
          accountId:
            type: string
          projectId:
            type: string
          rotationDays:
            type: integer
            minimum: 0
            maximum: 45
